# Redis配置
redis:
  host: 10.11.0.19
  port: 6379
  password: pGhQKwj7DE7FbFL1
  db: 15

# MySQL配置
mysql:
  host: localhost
  port: 3306
  username: root
  password: null
  database: null

# MongoDB配置
mongodb:
  host: 10.11.0.10
  port: 27017
  username: lxh
  password: admin123
  database: web-wechat

# OSS配置
oss:
  endpoint: oss.lxh.io
  accessKeyId: lxh
  accessKeySecret: lixunhuan
  bucket: web-wechat
  ssl: true

# ChatGPT配置
openai:
  enable: true
  apikey: xxxx # 在 https://beta.openai.com/account/api-keys 申请
  proxy: http://127.0.0.1:7890 # 代理
